# Generated by Django 2.2.3 on 2020-06-21 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200604_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
